name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Vet
      run: go vet -v .
      working-directory: ./easymongo

    - name: Build
      run: go build -v .
      working-directory: ./easymongo
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test package
      run: go test -v -race -covermode atomic -coverpkg=./... -coverprofile=coverage.out ./...

    - name: Convert code coverage for package
      uses: jandelgado/gcov2lcov-action@v1.0.5
      with:
        infile: coverage.out
        outfile: coverage.lcov

    - name: Upload code coverage to Coveralls for package
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov