name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Vet
      run: go vet -v .
      working-directory: ./easymongo

    - name: Build
      run: go build -v .
      working-directory: ./easymongo
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test easymongo
      run: go test -v -race -covermode atomic -coverprofile=coverage.1.out .
      working-directory: ./easymongo

    - name: Test mongotest
      run: go test -v -race -covermode atomic -coverprofile=coverage.2.out .
      working-directory: ./pkg/mongotest

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./easymongo/coverage.1.out
        flag-name: "easymongo"

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./pkg/mongotest/coverage.2.out
        flag-name: "mongotest"
        base-path: "pkg/mongotest"